# Generated by Django 4.0.4 on 2022-06-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_profile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Stewie_Griffin_edited.jpg', upload_to='profile_pics'),
        ),
    ]
