# Generated by Django 4.0.4 on 2022-08-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preference',
            field=models.TextField(default=True),
        ),
    ]
