# Generated by Django 4.0.4 on 2023-04-30 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_profile_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='reffered_by',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.CreateModel(
            name='Cashaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_code', models.CharField(default=None, max_length=20)),
                ('level_bonus', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('is_valid', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('refferals', models.ManyToManyField(default=None, to='users.profile')),
            ],
        ),
    ]
