# Generated by Django 4.0.4 on 2023-05-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_reffered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='mpesa_code',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
