# Generated by Django 4.0.4 on 2023-05-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_cashaccount_mpesa_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaccount',
            name='has_withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='withdraw_failed',
            field=models.BooleanField(default=False),
        ),
    ]
