# Generated by Django 4.0.4 on 2023-05-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_cashaccount_has_withdrawn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cashaccount')),
            ],
        ),
    ]
