# Generated by Django 4.0.4 on 2023-05-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_withdrawrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='mpesa_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
