# Generated by Django 4.0.4 on 2023-05-17 18:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_cashaccount_mpesa_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='mpesa_code',
            field=models.CharField(default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9|A-Z]{10}$', 'invalid code')]),
        ),
        migrations.CreateModel(
            name='Leveluprequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('mpesa_code', models.CharField(default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9|A-Z]{10}$', 'invalid code')])),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
