# Generated by Django 4.0.4 on 2024-10-16 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0017_profile_is_verified_profile_work_done'),
        ('blog', '0022_blogpost_assigned_to_blogpost_is_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_offer', models.BooleanField(default=False)),
                ('time_limit', models.DurationField()),
                ('job_status', models.CharField(choices=[('ASSIGNED', 'assigned'), ('OPEN', 'open'), ('COMPLETED', 'complete'), ('REVIEW', 'review')], default='OPEN', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OfferMilestones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('tags', models.CharField(choices=[('REQUIRED', 'required'), ('OPTIONAL', 'optional'), ('SUGGESTION', 'suggestion')], default=None, max_length=30, null=True)),
                ('extra_cash', models.IntegerField(default=0, null=True)),
                ('joboffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.joboffer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferBids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashbid', models.IntegerField(default=0)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('joboffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.joboffer')),
            ],
        ),
        migrations.AddField(
            model_name='joboffer',
            name='bids',
            field=models.ManyToManyField(related_name='job_bids', to='taskmanager.offerbids'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='milestones',
            field=models.ManyToManyField(related_name='job_milestones', to='taskmanager.offermilestones'),
        ),
    ]
