# Generated by Django 4.0.4 on 2024-10-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_alter_joboffer_options_alter_offerbids_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='job_bids', to='taskmanager.offerbids'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='milestones',
            field=models.ManyToManyField(blank=True, related_name='job_milestones', to='taskmanager.offermilestones'),
        ),
    ]
