# Generated by Django 4.0.4 on 2024-10-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_joboffer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermilestones',
            name='heading',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
