# Generated by Django 4.0.4 on 2024-10-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0006_alter_joboffer_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='accept_offer',
        ),
    ]
