# Generated by Django 4.0.4 on 2024-10-26 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_blogpost_price_offer'),
        ('taskmanager', '0008_alter_joboffer_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offer', to='blog.blogpost'),
        ),
    ]
