# Generated by Django 4.0.4 on 2024-10-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0009_alter_joboffer_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbids',
            name='bid_status',
            field=models.CharField(choices=[('WAITING', 'waiting'), ('ACCEPTED', 'accepted'), ('DECLINED', 'declined')], default='waiting', max_length=20),
        ),
    ]
