# Generated by Django 4.0.4 on 2022-08-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='spaces',
            field=models.CharField(choices=[('MUSIC & ART', 'MUSIC ART'), ('CYBER-SECURITY', 'CYBER OPS'), ('FOOD & LIFESTYLE', 'FOOD & LIFE'), ('LIFE HACKS AND JOBS', 'WORK & MONEY'), ('PROGRAMMING AND DATA SCIENCE', 'CODING')], default=True, max_length=30),
        ),
    ]
