# Generated by Django 4.0.4 on 2022-08-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_spaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='spaces',
            field=models.CharField(choices=[('MUSIC AND ART', 'MA'), ('CYBER-SECURITY', 'EH'), ('FOOD AND LIFESTYLE', 'FL'), ('LIFE HACKS AND JOBS', 'HJ'), ('PROGRAMMING AND DATA SCIENCE', 'CDS')], default=None, max_length=30),
        ),
    ]
