# Generated by Django 4.0.4 on 2023-04-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_spaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='spaces',
            field=models.CharField(choices=[('MUSIC AND ART', 'Music and Art'), ('CYBER-SECURITY', 'Ethical Hacking'), ('FOOD AND LIFESTYLE', 'Food and life'), ('LIFE HACKS AND JOBS', 'Money and Jobs'), ('PROGRAMMING AND DATA SCIENCE', 'Coding')], default=None, max_length=30),
        ),
    ]
