# Generated by Django 4.0.4 on 2023-05-01 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_alter_post_spaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('spaces', models.CharField(choices=[('MUSIC AND ART', 'Music and Art'), ('CYBER-SECURITY', 'Ethical Hacking'), ('FOOD AND LIFESTYLE', 'Food and life'), ('LIFE HACKS AND JOBS', 'Money and Jobs'), ('PROGRAMMING AND DATA SCIENCE', 'Coding')], default=None, max_length=30)),
                ('value', models.IntegerField(default=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
