# Generated by Django 4.0.4 on 2023-07-18 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_alter_blogpost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postreaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=10)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postreaction',
                'verbose_name_plural': 'Postreactions',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reaction',
            field=models.ManyToManyField(related_name='blogpost_reactions', through='blog.Postreaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
        ),
    ]
