# Generated by Django 4.0.4 on 2023-08-12 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_postreaction_blogpost_reaction_postreaction_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_date', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('spinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
