# Generated by Django 4.0.4 on 2024-02-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
