# Generated by Django 4.0.4 on 2024-03-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='ext_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
