# Generated by Django 4.0.4 on 2024-10-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_blogpost_ext_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='ext_url',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
