# Generated by Django 4.0.4 on 2024-10-16 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0021_alter_jobrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='blogpost_assignedto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
