# Generated by Django 4.0.4 on 2024-10-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_blogpost_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='price_offer',
            field=models.IntegerField(default=100),
        ),
    ]
